Fix Issue #350: Add test case for verifying the IfcMaterialLayerSet name (LayerSetName) in material test cases
buildingSMART/IDS pull request #351
Opened 2024-09-27 12:26 UTC by giuseppeverduciALMA

This pull request addresses the missing test case for verifying the name (LayerSetName) of the IfcMaterialLayerSet element in the material test cases.

Changes:
- updated the script.md file to include the new test case
- included the generated ids file
- added a sample IFC file that includes an IfcMaterialLayerSet with a defined value for the LayerSetName attribute
- updated the .gitignore file to prevent compiled files from being inadvertently added to the repository

2024-11-01 19:50 UTC, CBenghi commented on .gitignore
Hello @giuseppeverduciALMA,

Aren't these match expression a bit too broad? I'm concerned the will end up excluding useful files

2024-11-01 19:52 UTC, CBenghi requested changes
Content is ok, I'm unsure about the changes to the .gitignore file

2024-11-04 08:40 UTC, giuseppeverduciALMA commented on .gitignore
You're right to point that out; I see how the match expressions in the `.gitignore` could potentially be too broad. The intent was to exclude only generated and compiled files specific to the build process, especially those in the `SchemaProject` and `build` directories, which are recreated with each compilation and don't exist in the source repository.

For example, with a modification like this:

```
build/bin
build/obj
SchemaProject/bin
SchemaProject/obj
```

we would exclude only the files resulting from the compilation while still allowing the commit of the `SchemaProject/Ids.cs` file, which is autogenerated (would it be helpful to keep this file?).

How could we further refine these expressions to minimize any risk of excluding useful files?

2024-11-07 08:36 UTC, CBenghi commented on .gitignore
I think we already have similar matches in the current gitignore, I wonder if you need a local "git clean -xdf" and see if  you still have undesired artifacts after compilation.

2024-11-07 09:33 UTC, giuseppeverduciALMA commented on .gitignore
I've removed the two entries from the .gitignore after running the clean command. Thanks for the guidance!

2025-04-22 07:48 UTC, CBenghi approved these changes

2025-04-22 07:53 UTC, merged